baseURL = "http://recordssoundthesame.com/"
languageCode = "en-gb"
title = "Records Sound the Same"
theme = "rsts"
publishDir = "DEPLOY"
paginate = 12
copyright = "All content is copyright Records Sound the Same Ltd"


[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[author]
    name = "Records Sound the Same"
    email = "hello@recordssoundthesame.com"

[taxonomies]
